use serde::Serialize;

/// Categories for AI-generated meeting notes.
#[derive(Debug, Clone, Serialize)]
pub enum NoteType {
    KeyPoint,
    Decision,
    Risk,
    ActionItem,
}

/// A single note entry generated by the AI.
#[derive(Debug, Clone, Serialize)]
pub struct NoteEntry {
    pub note_type: NoteType,
    pub content: String,
}

/// Manages AI-powered note generation from meeting transcripts.
pub struct NoteEngine {
    _entries: Vec<NoteEntry>,
}

impl NoteEngine {
    pub fn new() -> Self {
        Self {
            _entries: Vec::new(),
        }
    }
}

impl Default for NoteEngine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn creates_note_engine() {
        let engine = NoteEngine::new();
        assert!(engine._entries.is_empty());
    }
}
